### ISSUE TITLE
allways  hold in queued  when get metrics from bosh-expoter 

### ISSUE THREAD

**Issue by leolzbing521** [bosh-prometheus/bosh_exporter#16]
Dear all,
          deployment bosh-prometheus 23 version in pivotal 2.0, tasks allways  hold in queued  when get metrics from bosh-expoter.
           bosh-exporter->director ->get state ，may be time waiting for director get state .SOS
![1906012122](https://user-images.githubusercontent.com/5356341/37014037-d6c7ea24-2138-11e8-8ef6-59df5383c62e.jpg)

**Comment by leolzbing521** [comment]
I set scrape_interval:10m ,may be well.

**Comment by leolzbing521** [comment]
![1894715490](https://user-images.githubusercontent.com/5356341/37337656-f041acb2-26ef-11e8-85db-67f06480c143.jpg)

**Comment by leolzbing521** [comment]
bosh exporter  queue 17111 tasks，how can I fix. @frodenas

**Comment by frodenas** [comment]
ssh into your bosh vm, become `root` and run a `monit restart director`. Most likely there are hung db connections and the workers cannot process the requests. After some minutes, all tasks should be processed.

**Comment by frodenas** [comment]
Please reopen if problem still persists.
