### ISSUE TITLE
How to choose IP when multiple are available ?

### ISSUE THREAD

**Issue by psycofdj** [bosh-prometheus/bosh_exporter#17]
Hi,

Is there a way to configure bosh_exporter to select a particular IP when multiple IPs are available for a  bosh-instance ? 

In my use-case, one of my deployed instance has two IPs:
 * a public IP accessible from prometheus' deployment
 * a private IP, inaccessible from prometheus

Unfortunately, bosh_exporter takes the private IP when dumping `bosh_target_groups.json` file which lead to an unreachable node in prometheus.

From what I understand in the code [here](https://github.com/bosh-prometheus/bosh_exporter/blob/master/collectors/jobs_collector.go#L543) and [here](https://github.com/bosh-prometheus/bosh_exporter/blob/d4a4c853dfbaf62a128372263421eb6f53c02aa7/collectors/service_discovery_collector.go#L152), the behavior seems hard-coded but maybe I'm missing something.

If no known workaround is available, are you willing my contribution on this feature ?

**Comment by frodenas** [comment]
Sure, all help is appreciated.
