### ISSUE TITLE
bosh_exporter unable to cf push or unable use binary

### ISSUE THREAD

**Issue by deshab** [bosh-prometheus/bosh_exporter#26]
Hi Team - We are in the process of using BOSH_EXPORTER, unable to push to cf and also unable to use binay, getting below error for both ways.: Coyld you please share some insight what could be the reason?
**from Binary:**
ERRO[0000] Error creating BOSH Client: Fetching info: Unmarshaling Director response: invalid character '<' looking for beginning of value  source="bosh_exporter.go:273"

**From cf push:**
2019-02-28T17:23:31.38-0500 [APP/PROC/WEB/0] ERR time="2019-02-28T22:23:31Z" level=error msg="Error creating BOSH Client: Fetching info: Unmarshaling Director response: invalid character '<' looking for beginning of value" source="bosh_exporter.go:273"

**Manifestfile:**
applications:
  - name: bosh-exporter
    buildpack: go_buildpack
    env:
      BOSH_EXPORTER_BOSH_URL: "https://172.18.26.15:8443"
      BOSH_EXPORTER_BOSH_USERNAME: "UAA_ADMIN"
      BOSH_EXPORTER_BOSH_PASSWORD: "UAA_ADMIN_PASS"
      BOSH_EXPORTER_BOSH_CA_CERT_FILE: "root_ca_certificate"
      BOSH_EXPORTER_BOSH_LOG_LEVEL: "DEBUG"

**Comment by frodenas** [comment]
The port at `"https://172.18.26.15:8443` seems wrong, usually, the bosh director listens at port `25555`.

**Comment by deshab** [comment]
Thanks for the input. Still didn't get success...
Could you please provide clarity on what user/pass we need to use?
1) Uaa Admin User Credentials
2) Uaa Login Client Credentials
3) Bosh Commandline Credentials
4) Director Credentials

**Comment by frodenas** [comment]
You can use the Bosh Commandline Credentials.

**Comment by benjaminguttmann-avtq** [comment]
Closed due to inactivity, feel free to reopen
