### ISSUE TITLE
How to generate ca cert file.

### ISSUE THREAD

**Issue by MatthewPJ** [bosh-prometheus/bosh_exporter#29]
Hi,

bosh.ca-cert-file is required, but can you advise how to generate this file?

**Comment by gordcorp** [comment]
It's likely the same ca cert from creds.yml you use with `bosh alias-env` - https://bosh.io/docs/cli-v2/#alias-env

**Comment by benjaminguttmann-avtq** [comment]
@MatthewPJ @gordcorp is correct, that is the same ca_cert you use for alias-env
