### ISSUE TITLE
bosh_collector.go:174

### ISSUE THREAD

**Issue by gitmedur** [bosh-prometheus/bosh_exporter#31]
Hi,
After first scrape, i get this log and metrics endpoint becomes unreachable..
INFO[0000] Starting bosh_exporter (version=, branch=, revision=)  source="bosh_exporter.go:277"
INFO[0000] Build context (go=go1.13.8, user=, date=)     source="bosh_exporter.go:278"
INFO[0000] Using BOSH Director `p-bosh` (4f88432b-dfd0-4a44-a832-aab4b0231c4e)  source="bosh_exporter.go:291"
INFO[0000] Listening on :9190                            source="bosh_exporter.go:365"
DEBU[0039] Reading deployments...                        source="deployments_filter.go:35"
DEBU[0039] Reading Instances for deployment `service-instance_1d48aca8-255b-4548-b1c5-XYZ`:  source="deployments_fetcher.go:81"
DEBU[0039] Reading Instances for deployment `harbor-container-registry-bb62f67ccaaABC`:  source="deployments_fetcher.go:81"
DEBU[0039] Reading Instances for deployment `pivotal-container-service-6db72fec9365DEF`:  source="deployments_fetcher.go:81"
DEBU[0041] Reading Releases for deployment `harbor-container-registry-bb62f67ccaaABC`:  source="deployments_fetcher.go:165"
DEBU[0041] Reading Stemcells for deployment `harbor-container-registry-bb62f67ccaaABC`:  source="deployments_fetcher.go:185"
DEBU[0042] Reading Releases for deployment `service-instance_1d48aca8-255b-4548-XYZ`:  source="deployments_fetcher.go:165"
DEBU[0042] Reading Stemcells for deployment `service-instance_1d48aca8-255b-4548-XYZ`:  source="deployments_fetcher.go:185"
DEBU[0042] Reading Releases for deployment `pivotal-container-service-6db72fec9365DEF`:  source="deployments_fetcher.go:165"
DEBU[0042] Reading Stemcells for deployment `pivotal-container-service-6db72fec9365DEF`:  source="deployments_fetcher.go:185"
ERRO[0042] rename /tmp/bosh_target_groups.json355655166 bosh_target_groups.json: invalid cross-device link  source="bosh_collector.go:174"
panic: send on closed channel

goroutine 252 [running]:
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*metricMap).Collect(0xc00012ea50, 0xc000160f00)
        /home/centos/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/prometheus/client_golang/prometheus/vec.go:232 +0x15e
github.com/bosh-prometheus/bosh_exporter/collectors.(*JobsCollector).Collect(0xc00028a000, 0xc00036e420, 0x3, 0x4, 0xc000160f00, 0x0, 0x0)
        /home/centos/go/src/github.com/bosh-prometheus/bosh_exporter/collectors/jobs_collector.go:472 +0x432
github.com/bosh-prometheus/bosh_exporter/collectors.(*BoshCollector).executeCollectors.func1(0xc000348b60, 0xc00036e420, 0x3, 0x4, 0xc000160f00, 0xc0004c1920, 0xb68440, 0xc00028a000)
        /home/centos/go/src/github.com/bosh-prometheus/bosh_exporter/collectors/bosh_collector.go:204 +0xb4
created by github.com/bosh-prometheus/bosh_exporter/collectors.(*BoshCollector).executeCollectors
        /home/centos/go/src/github.com/bosh-prometheus/bosh_exporter/collectors/bosh_collector.go:202 +0x174

How can i move forward?
Thanks

**Comment by kskurtveit** [comment]
Hi,

Me and my co-worker looked at this and the bosh_exporter tries to rename the bosh_target_groups like this:

(We modded the go library so we could see what it tried to rename)
From: /tmp/bosh_target_groups.json2030290237 To: bosh_target_groups.json.

Be aware that it does not say where it stores the renamed file, so by adding the parameter sd.filename and specify the full path like this: ./bosh_exporter --sd.filename="/tmp/bosh_target_groups.json" it successfully renames the file, and it doesn't crash.
