### ISSUE TITLE
Why bosh_exporter uses bosh tasks instead of using bosh deployment manifests?

### ISSUE THREAD

**Issue by kinjelom** [bosh-prometheus/bosh_exporter#39]
Bosh task is a heavy async mechanism to long running jobs.
As far as I know bosh_exporter uses it to service discovery, but we can:
- get all deployments `bosh curl /deployments | jq .[].name`
- get every deployment manifest `bosh curl /deployments/deployment_name | jq .manifest -r | yq`
- extract: `deployment_name`, `instance_groups`, `jobs`
- use bosh-query to ask for metrics `curl http://q-s0.instance_groups.default.deployment_name.bosh:port`

What is missing?

**Comment by benjaminguttmann-avtq** [comment]
@kinjelom thank you for your question. One thing I can see that the approach described above uses the latest successfully deployed state but not the actual state. What I means is if you deployment breaks in the middle and e.g. have the instance_groups have a new stemcell already your approach will not show that but the current approach will show that. 

In general I think when the bosh_exporter was originally created `bosh curl` was not a thing yet. Nevertheless we will look into your suggestion and see if we can improve the bosh_exporter :)

**Comment by psycofdj** [comment]
The bosh_exporter don't explicitly use bosh tasks. It actually use [bosh CLI](https://bosh.io/docs/cli-v2/) bindings which are using bosh tasks for some of the commands.

Also, the only bosh CLI commands that triggers an async bosh task is to fetch instance metrics. Only bosh director is able to communicates with VM agent to fetch this information, the exporter would not be able to "connect" to each VM though the suggested dns `http://q-s0.instance_groups.default.deployment_name.bosh:port` (or we would have to re-implement a significant part of director's works, which is not the goal).
