### ISSUE TITLE
What is the GO version required to make a build of my own

### ISSUE THREAD

**Issue by anandbommakanti** [bosh-prometheus/bosh_exporter#57]
What is the GO version required to make a build of our own BOSH Exporter? Is there a compatibility matrix information?

**Comment by psycofdj** [comment]
The exporter is currently built with go 1.20

**Comment by psycofdj** [comment]
There is no compatibility matrix, min go version is given in go.mod file

**Comment by anandbommakanti** [comment]
Thank You.
