### ISSUE TITLE
bosh queued tasks metrics

### ISSUE THREAD

**Issue by poblin-orange** [bosh-prometheus/bosh_exporter#9]
Following a recent outage (iaas failure resulting in bosh hm posting hundreds of "scan and fix" tasks, having a metric giving the bosh queue length metrics would be very valuable. We could combine it with a "meltdown" alert in prometheus bosh release.

**Comment by frodenas** [comment]
@poblin-orange I'm just in the middle of refactoring. I'll take a look at this when I finish it and see what metrics we can get.

**Comment by amuessig** [comment]
@frodenas Was there any progress on that?

**Comment by benjaminguttmann-avtq** [comment]
I think the bosh queue length is meanwhile available via bosh metrics server endpoint, there I will go ahead and close this issue here.
